# Linux builds take the Khronos Vulkan headers from the Android NDK the Android
# side already needs, so no distribution Vulkan SDK/devel package is required.
# Only vulkan/ and vk_video/ are copied: the whole sysroot would shadow glibc.
function(axrb_linux_vulkan_headers out_dir)
  set(AXRB_VULKAN_HEADERS "" CACHE PATH "Optional Vulkan headers directory")
  if(AXRB_VULKAN_HEADERS)
    set(${out_dir} "${AXRB_VULKAN_HEADERS}" PARENT_SCOPE)
    return()
  endif()
  set(_sdk "$ENV{ANDROID_HOME}")
  if(NOT _sdk)
    set(_sdk "$ENV{HOME}/Android/Sdk")
  endif()
  file(GLOB _ndk_includes "${_sdk}/ndk/*/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include")
  list(SORT _ndk_includes COMPARE NATURAL ORDER DESCENDING)
  if(NOT _ndk_includes)
    message(FATAL_ERROR "Install an Android NDK or set AXRB_VULKAN_HEADERS")
  endif()
  list(GET _ndk_includes 0 _ndk_include)
  file(COPY "${_ndk_include}/vulkan" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/vulkan-headers")
  if(EXISTS "${_ndk_include}/vk_video")
    file(COPY "${_ndk_include}/vk_video" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/vulkan-headers")
  endif()
  set(${out_dir} "${CMAKE_CURRENT_BINARY_DIR}/vulkan-headers" PARENT_SCOPE)
endfunction()
